"""
Copyright (C) 2007 Matthew Turk.  All Rights Reserved.

This file is part of yt.

yt is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""


# This file is generated by /afs/slac.stanford.edu/g/ki/ki02/mturk/Research/enzo/tools/yt/setup.py
# It contains system_info results at the time of building this package.
__all__ = ["get_info","show"]


def get_info(name):
    g=globals()
    return g.get(name,g.get(name+"_info",{}))

def show():
    for name,info_dict in globals().items():
        if name[0]=="_" or type(info_dict) is not type({}): continue
        print name+":"
        if not info_dict:
            print "  NOT AVAILABLE"
        for k,v in info_dict.items():
            v = str(v)
            if k=='sources' and len(v)>200: v = v[:60]+' ...\n... '+v[-60:]
            print '    %s = %s'%(k,v)
        print
    return
    