import os
import runpy
from tempfile import TemporaryDirectory

import yaml

import yt.utilities.mesh_code_generation as mcg


with open(os.path.join(os.path.dirname(mcg.__file__), "mesh_types.yaml")) as stream:
    _MESH_TYPES = yaml.load(stream, Loader=yaml.FullLoader)


def test_mesh_code_generator_builds_expected_2d_function_strings():
    generator = mcg.MeshCodeGenerator(_MESH_TYPES["Quad4"])

    function_code, jacobian_code = generator.get_interpolator_definition()
    function_decl, jacobian_decl = generator.get_interpolator_declaration()

    assert generator.function_name == "Q1Function2D"
    assert generator.jacobian_name == "Q1Jacobian2D"
    assert "cdef void Q1Function2D" in function_code
    assert "cdef void Q1Jacobian2D" in jacobian_code
    assert "rcol" in jacobian_code and "scol" in jacobian_code
    assert "tcol" not in jacobian_code
    assert function_decl == mcg.fun_dec_template % "Q1Function2D"
    assert jacobian_decl == mcg.jac_dec_template_2D % "Q1Jacobian2D"


def test_mesh_code_generator_builds_expected_3d_function_strings():
    generator = mcg.MeshCodeGenerator(_MESH_TYPES["Hex8"])

    function_code, jacobian_code = generator.get_interpolator_definition()
    function_decl, jacobian_decl = generator.get_interpolator_declaration()

    assert generator.function_name == "Q1Function3D"
    assert generator.jacobian_name == "Q1Jacobian3D"
    assert "cdef void Q1Function3D" in function_code
    assert "cdef void Q1Jacobian3D" in jacobian_code
    assert "rcol" in jacobian_code and "scol" in jacobian_code and "tcol" in jacobian_code
    assert function_decl == mcg.fun_dec_template % "Q1Function3D"
    assert jacobian_decl == mcg.jac_dec_template_3D % "Q1Jacobian3D"


def test_mesh_code_generator_currently_allows_non_2d_3d_mesh_without_jacobian_templates():
    generator = mcg.MeshCodeGenerator(
        {
            "mesh_type": "L1",
            "num_dim": 1,
            "num_vertices": 2,
            "num_mapped_coords": 1,
            "shape_functions": "[1 - x[0], x[0]]",
        }
    )

    assert generator.function_name == "L1Function1D"
    assert generator.jacobian_name == "L1Jacobian1D"
    assert not hasattr(generator, "jacobian_header")


def test_mesh_code_generation_main_writes_declarations_and_definitions():
    original_cwd = os.getcwd()
    try:
        with TemporaryDirectory() as tmpdir:
            os.chdir(tmpdir)
            os.mkdir("lib")
            with open("mesh_types.yaml", "w") as stream:
                yaml.dump(_MESH_TYPES, stream)

            runpy.run_path(mcg.__file__, run_name="__main__")

            with open("lib/autogenerated_element_samplers.pyx") as stream:
                pyx_contents = stream.read()
            with open("lib/autogenerated_element_samplers.pxd") as stream:
                pxd_contents = stream.read()

            assert mcg.file_header in pyx_contents
            assert "cimport cython" in pyx_contents
            assert "Q1Function2D" in pyx_contents
            assert "Q1Jacobian3D" in pyx_contents
            assert "Q1Function2D" in pxd_contents
            assert "Q1Jacobian3D" in pxd_contents
    finally:
        os.chdir(original_cwd)
