name: Dead code detection
on: [pull_request]

jobs:
  vulture:
    name: vulture
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: install
      id: install
      run : pip install vulture

    - name: check
      id: vulture
      run: |
        vulture --version
        vulture yt --sort-by-size --min-confidence 100 --exclude "**/api.py" --exclude "yt/extern"