name: docs build

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pandoc and doxygen
        run: |
          sudo apt install pandoc doxygen

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          # this path is specific to Ubuntu
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r ./requirements.txt

      - name: Build docs
        run: |
          cd docs/
          make SPHINXOPTS=-v html

      - name: Check links
        run: |
          cd docs/
          make SPHINXOPTS=-v linkcheck
